Try swap button
S010MON/Bamboo pull request #143
Opened 2022-01-03 15:57 UTC by shirleydekoster

2022-01-03 18:25 UTC, S010MON commented
This is currently failing to compile, please address the compilation issues indicated in the tests and try pushing again.

Also, can you please rename the PR to something more accurate like "_Swap_toggle/start_button_"

2022-01-04 08:50 UTC, AlexHartmann00 reviewed
Works great, I was thinking about changing the label of the Toggle button? I dont think its very intuitive

2022-01-04 10:23 UTC, S010MON requested changes
Update the image to a picture of the colours being swapped and this will be approved

2022-01-04 15:08 UTC, S010MON approved these changes

2022-01-06 10:29 UTC, merged