Deep copy
S010MON/Bamboo pull request #41
Opened 2021-09-22 11:08 UTC by terraarret

done with hard copy of the grid and tetings

2021-09-22 14:58 UTC, S010MON requested changes

2021-09-22 14:58 UTC, S010MON commented on app/src/main/java/Bamboo/model/GridHashImp.java
> +        Grid copy = new GridArrayImp(radius);
This is in GridHashImp, but it returns a GridArrayImp ???

2021-09-22 14:58 UTC, S010MON commented on app/src/test/java/Bamboo/TestDeepCopyArrImp.java
> +
There is random white space here ... why?

2021-09-22 14:58 UTC, S010MON commented on app/src/test/java/Bamboo/TestDeepCopyHashMapImp.java
> +}
You should always leave a new (blank) line at the end of the file, this can cause errors if it's not done

2021-09-23 12:16 UTC, terraarret commented
corrections made since previous pull request

2021-09-23 13:17 UTC, S010MON requested changes

2021-09-23 13:17 UTC, S010MON commented on app/src/test/java/Bamboo/TestDeepCopyArrImp.java
> +        Vector v = new Vector(-1,-1,0);
This is an invalid vector so the test cannot pass

2021-09-23 13:17 UTC, S010MON commented on app/src/test/java/Bamboo/TestDeepCopyHashMapImp.java
> +        Vector v = new Vector(1, 1, 0);
Not a valid vector ...

2021-10-05 12:45 UTC, closed without merging